# Generated by Django 4.2.11 on 2025-02-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_content_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='url_name',
            field=models.TextField(),
        ),
    ]
