# Generated by Django 4.2.11 on 2025-02-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_content_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='url_name',
            field=models.CharField(max_length=50),
        ),
    ]
