# Generated by Django 4.2.11 on 2025-02-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_content_title_alter_content_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(default='sadsa'),
        ),
    ]
