# Generated by Django 4.2.11 on 2025-02-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_content_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.CharField(default='Author placeholder', max_length=50),
        ),
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(default='book', max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(default='Description placeholder'),
        ),
    ]
