# Generated by Django 4.2.11 on 2025-02-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_content_author_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='review',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
