# Generated by Django 4.2.11 on 2025-02-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_review_rating_post_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='url_name',
            field=models.CharField(default='e', max_length=20),
            preserve_default=False,
        ),
    ]
